# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Perl6-Contexts
version:      0.4
version_from: Contexts.pm
installdirs:  site
requires:
    B::Generate:                   1.06

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
